language: node_js

node_js:
  - '18'

script: npm test

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
  - npm run codecov

addons:
  chrome: stable

dist: trusty

sudo: required
